config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'chart', to: 'pages#chart'
  get "component", to: "pages#component"
  resources :portfolios, only: %i[index show create update destroy] do
    resources :transactions, only: :index
  end
  get "/component", to: "pages#component"

  get "/addresses/:id", to: "addresses#show"
  resources :transactions, only: :show
  resources :addresses, only: %i[show create destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :portfolio

  validates :public_key, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :portfolio
end

app/models/message_vote.rb
class MessageVote < ApplicationRecord
  belongs_to :user
  belongs_to :portfolio_message
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  has_many :addresses
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
end

app/models/portfolio_message.rb
class PortfolioMessage < ApplicationRecord
  belongs_to :portfolio
  belongs_to :user

  validates :message, presence: true
end

app/models/portfollio_address.rb
class PortfollioAddress < ApplicationRecord
  belongs_to :portfolio
  belongs_to :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :portfolios
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def show
    @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    if @address.save!
      Thread.new do
        RestClient.post("https://api.blockcypher.com/v1/btc/main/wallets/portfolio#{@address.portfolio.id}/addresses?token=45533959044c4f84b7e75039c257110c",
          {
            addresses: [@address.public_key]
          }.to_json,
          content_type: :json
        )
      end
      redirect_to portfolio_path(@address.portfolio)
    else
      render 'portfolios/show', status: :unprocessable_entity
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to portfolio_path, status: :see_other
  end


  private

  def address_params
    params.require(:address).permit(:public_key, :blockchain, :portfolio_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/messages_votes_controller.rb
class MessagesVotesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @portfolio = Portfolio.new
  end

  def chart
  end

  def component
  end
end

app/controllers/portfolio_addresses_controller.rb
class PortfolioAddressesController < ApplicationController
end

app/controllers/portfolio_messages_controller.rb
class PortfolioMessagesController < ApplicationController
end

app/controllers/portfolios_controller.rb
require 'rest-client'

class PortfoliosController < ApplicationController
  def index
    # return all portfolios for the current user
    @user = current_user
    @user_portfolios = current_user.portfolios
    @new_portfolio = Portfolio.new
  end

  def show
    @address = Address.new
    @portfolio = Portfolio.find(params[:id])
  end

  def create
    @portfolio = Portfolio.new(params_portfolio)
    @portfolio.user = current_user if user_signed_in?
    @portfolio.name = 'Untitled portfolio' unless @portfolio.name

    if @portfolio.save!
      Thread.new do
        RestClient.post("https://api.blockcypher.com/v1/btc/main/wallets?token=45533959044c4f84b7e75039c257110c",
          {
            name: "portfolio#{@portfolio.id}",
            addresses: @portfolio.addresses.map { |address| address.public_key }
          }.to_json,
          content_type: :json
        )
      end
      redirect_to portfolio_path(@portfolio)
    else
      render 'pages/home', status: :unprocessable_entity
    end
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    @portfolio.update(params_portfolio)
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.addresses.destroy_all
    @portfolio.destroy

    redirect_to portfolios_path
  end

  private

  def params_portfolio
    params.require(:portfolio).permit(:id, :name, addresses_attributes: [:id, :public_key, :_destroy])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/addresses/show.html.erb
<div data-controller="addresses" data-addresses-address-value="<%= @address.public_key %>">
  <div class="banner" style="background-image: url(<%= image_path('background-color.jpg') %>); padding-inline: 2.5vw; padding-bottom: 2%; min-height: 55vh; padding-top: 115px;">
    <div class="d-flex justify-content-around">



      <div class="overview-address">
        <div class="container formcontainerbugfix">
          <div class="d-flex justify-content-between align-items-center">
            <div class="crypto-icon">
              <%= image_tag "btc.png" %>
            </div>
            <div class="currency d-flex flex-column align-items-end">

              <div class="name">BITCOIN</div>
              <div class="text-success" data-addresses-target="change"></div>
            </div>
          </div>
          <div class="address text-break mt-4"><%= @address.public_key %></div>
          <div class="separate"></div>
          <div class="transactions">
            <div class="d-flex justify-content-around align-items-center">
              <i class="fa-solid fa-square-plus text-success"></i>
              <div class="d-flex flex-column align-items-end">
                <h3 class="text-success">INCOMING</h3>
                <div class="balance" data-addresses-target="incoming"><i class="fa-solid fa-arrow-left"></i></div>
              </div>
            </div>
            <div class="d-flex justify-content-around align-items-center mt-3">
              <i class="fa-solid fa-square-minus text-danger"></i>
              <div class="d-flex flex-column align-items-end">
                <h3 class="text-danger">OUTGOING</h3>
                <div class="balance" data-addresses-target="outgoing"><i class="fa-solid fa-arrow-right"></i></div>
              </div>
            </div>
          </div>
          <div class="separate"></div>
        </div>
      </div>





      <div class="chart-address bg-dark-grey d-flex align-items-center" style="min-height: 47vh; border-radius: 20px; position: relative;">
        <div class="logo-bitcoin2 d-flex">
          <%= image_tag('btc1.png', size:"80")%>
          <h2 data-addresses-target="value" style="font-size: 35px; margin-left: 20px;"></h2>
        </div>
        <canvas id="portfolioCanvas" aria-label="chart" role="img" class="my-auto">
          <h1> TOTAL BITCOIN</h1>
        </canvas>
      </div>
    </div>
  </div>

  <div class="transactions-height bg-dark-grey">
    <div class="container p-5">
      <div class="d-flex align-items-center justify-content-between mb-4">
        <h2>RECENT TRANSACTIONS</h2>
        <a href="<%= portfolio_path(@address.portfolio) %>" class="d-flex link-white">
          <i class="fa-solid fa-arrow-left p-1"></i>PORTFOLIO
        </a>
      </div>
      <div data-addresses-target="transactions">
      </div>

    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="image" content="<%= image_path('cryptocurrency.jpg', size: '1200x630') %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "cryptocurrency128.png", rel: "icon", type: "image/png" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300&display=swap" rel="stylesheet">
  </head>

  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
      <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/chart.html.erb
<div class="chart-container">
  <canvas id="portfolioCanvas" aria-label="chart" role="img">
    <h1> TOTAL BITCOIN</h1>
  </canvas>
</div>

app/views/pages/component.html.erb
<div class="container-address">
  <div class="icone-title">
    <%= image_tag("btc.png", class: "img-bitcoin") %>
    <h2><strong>BITCOIN</strong></h2>
  </div>
  <div class="key-balance">
    <p>1KK954BCS4NuKmp...</p>
    <h2><strong>12322$</strong></h2>
  </div>
</div>

<div class="container-transaction">
  <div class="top-transaction">
    <p><strong class="strong-white">FROM : </strong>1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa</p>
    <p class="strong-white"><strong>8h02 - 01/03/2023</strong></p>
  </div>
    <p><strong class="strong-white">TO : </strong>1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2</p>
  <div class="bottom-transaction">
      <p class="btc-yellow"><strong>0,635142 BTC</strong></p>
      <p class="loading"><strong>PENDING</strong></p>
  </div>
</div>

<div class="container-team">
  <div class="team-left">
    <h3><strong>LAFARGUE</strong></h3>
    <h3><strong>Thibault</strong></h3>
    <p class="status-grey">Lead Dev</p>
  </div>
  <%= image_tag("thibault.png", class: "img-team")%>
</div>

<div class="container-portfolio">
  <%= image_tag("btc2.png", class: "img-portfolio")%>
  <h4 class="text-white">TOP 50 CRYPTO TRADER</h4>
  <h4 class="text-white"> : </h4>
  <h4 class="text-white">86</h4>
  <h4 class="text-white">addresses</h4>
  <i class="fas fa-trash m-3"></i>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <video autoplay loop muted plays-inline class="back-video">
    <source src="backcolor.mp4" type="video/mp4">
  </video>

  <div class="d-flex banner-display">
    <div class="container">
      <h1 class="first-title">YOUR CRYPTO AT A GLANCE WITH COINS</h1>
      <h4 class="sub-title">Generate your free dashboard in 5 minutes !</h4>
      <a class="start-btn font-btn" href="#bottom-page">START</a>
    </div>
    <div class="container img-align">
      <iframe src='https://my.spline.design/cryptoanno-435ba6783c0e78e386c0ca480e19ce99/' class="imgspline2"></iframe>
    </div>
  </div>
</div>

<div class="d-flex banner-add" style="background-color: rgb(21 21 21)">
  <div class="position-cache">
        <iframe src='https://my.spline.design/untitled-f53ed9f96027b1afe0a1657257688a16/' frameborder='0' width='100%' height='100%' class="imgform spline-watermark"></iframe>
  </div>

  <div>
    <h1 class="title title-search font-rainbows">ADD YOUR CRYPTO !</h1>
    <div class="container">
      <div class="row">

        <%= form_with model: @portfolio, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
          <template data-nested-form-target="template">
            <%= f.fields_for :addresses, Address.new, child_index: 'NEW_RECORD' do |address_fields| %>
              <%= render "shared/address_form", f: address_fields %>
            <% end %>
          </template>

          <%= f.fields_for :addresses, Address.new do |address_fields| %>
            <%= render "shared/address_form", f: address_fields %>
          <% end %>

          <div data-nested-form-target="target"></div>


          <div class="display-div-add-and-go">
          <button type="button" class="btn-home-fome" data-action="nested-form#add">+</button>
            <%= f.submit "Go !", class: "btn-go-form" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="bottom-page" class="team" style="background-color: rgb(21 21 21)">
  <h1 class="title-card font-rainbows format-title-team">THE TEAM</h1>
    <div class="display-card">
      <div class="container-team">
        <div class="team-left">
          <h3 class="forma-card-team"><strong>LAFARGUE</strong></h3>
          <h3 class="sub-title-team"><strong>Thibault</strong></h3>
          <p class="status-grey">CEO</p>
        </div>
        <%= image_tag("thibault.png", class: "img-team")%>
      </div>
      <div class="container-team">
        <div class="team-left">
          <h3 class="forma-card-team"><strong>BOISTAULT</strong></h3>
          <h3 class="sub-title-team"><strong>Enzo</strong></h3>
          <p class="status-grey">co-CPO</p>
        </div>
        <%= image_tag("enzo.png", class: "img-team")%>
      </div>
      <div class="container-team">
        <div class="team-left">
          <h3 class="forma-card-team"><strong>RAIMBAULT</strong></h3>
          <h3 class="sub-title-team"><strong>FX</strong></h3>
          <p class="status-grey">co-CPO</p>
        </div>
        <%= image_tag("fx-v2.png", class: "img-team")%>
      </div>
      <div class="container-team">
        <div class="team-left">
          <h3 class="forma-card-team"><strong>ETORI</strong></h3>
          <h3 class="sub-title-team"><strong>Irvin</strong></h3>
          <p class="status-grey">CTO</p>
        </div>
        <%= image_tag("irvin-v2.png", class: "img-team")%>
      </div>
    </div>

</div>

app/views/portfolios/index.html.erb
<div>
     <video autoplay loop muted plays-inline class="back-video">
      <source src="backcolor.mp4" type="video/mp4">
     </video>

      <div class='wrapper-banner banner-profil'>
        <div class="row d-flex justify-content-center container-banner">
          <div class="card-profile-banner p-3 py-4">
            <div class="text-center">
              <%= image_tag("thibovf.png", size: '80x80', class: 'profile-image')%>
            </div>
            <div class="text-center mt-3">
              <h2 class="mt-2 mb-0 profile-name"> <%= current_user.username.capitalize %></h5>
              <p class='profession-title'>Crypto enthusiast #HODL</p>
            </div>
          </div>
        </div>
      </div>


<div class="bg-dark-grey">
    <div class="container p-5 d-flex">

      <div class="width-wallet">
          <div class="display-title-x-button">
            <h2 class='text-white font-rainbows'> Portfolios</h2>
            <a href="#" class="btn-pink" data-bs-toggle="modal" data-bs-target="#portfolioModal">+</a>
          </div>


          <div class="profile-content bg-dark-grey">
            <div>
              <%  @user_portfolios.order(created_at: :desc).each do |portfolio| %>
                <div class="container-portfolio-profile mt-3">
                  <%= link_to portfolio_path(portfolio), style: "text-decoration:none;", class: "d-flex justify-content-between align-items-center flex-grow-1" do %>
                      <div class="list-info-title">
                        <%= image_tag("btc2.png", class: "img-portfolio")%>
                        <h4 class="text-card-wallet"> <%= portfolio.name.upcase %></h4>
                      </div>
                      <div class="list-info justify-self-end">
                        <h4 id="num"><%= portfolio.addresses.count %></h4>
                      </div>
                  <% end %>
                  <div class="d-flex justify-content-between align-items-center">
                        <h4 class="text-card-wallet2" style="margin-right: 10px;"> <%= portfolio.addresses.count > 1 ? 'addresses' : 'address' %> </h4>
                        <%= link_to portfolio_path(portfolio), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{portfolio.name}?" } do %>
                          <i class="fas fa-trash m-3 trash-icone-value"></i>
                        <% end %>
                      </div>
                  </div>
              <% end %>
            </div>
          </div>



        </div>


        <div class="chart-view">
          <div class="display-title-x-button">
            <h2 class='text-white font-rainbows'>Distribution</h2>
          </div>
          <div class="chartCard">
            <div class="chartBox" data-controller="portfolios-distribution" data-portfolios-distribution-portfolios-value="<%= @user_portfolios.map { |portfolio| portfolio.name.upcase } %>" data-portfolios-distribution-addresses-value="<%= @user_portfolios.map { |portfolio| portfolio.addresses.count } %>">
              <canvas class="mx-4" id="viewCanvas" aria-label="distributionChart" role="img"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="portfolioModal" tabindex="-1" aria-labelledby="portfolioModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="portfolioModalLabel">NEW PORTFOLIO</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with model: @new_portfolio, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
        <div class="modal-body">
          <template data-nested-form-target="template">
            <%= f.fields_for :addresses, Address.new, child_index: 'NEW_RECORD' do |address_fields| %>
              <%= render "shared/address_form", f: address_fields %>
            <% end %>
          </template>

          <%= f.text_field :name, class: "form-control-v2", placeholder: "Untitled portfolio" %>

          <h6 class="text-white mt-4">Addresses</h6>

          <%= f.fields_for :addresses, Address.new do |address_fields| %>
            <%= render "shared/address_form", f: address_fields %>
          <% end %>

          <!-- Inserted elements will be injected before that target. -->
          <div data-nested-form-target="target"></div>
        </div>

        <div class="modal-footer">
          <a href="#" class="btn-pink" data-action="nested-form#add">Add address</a>
          <%= f.submit 'Save portfolio', class: "btn-pink" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolios/show.html.erb
<div data-controller="portfolios" data-portfolios-address-value="portfolio<%= @portfolio.id %>">
  <div class="banner" style="background-image: url(<%= image_path('background-color.jpg') %>); padding-inline: 2.5vw; height: 63vh; padding-top: 115px;">
    <div class="d-flex justify-content-around">
      <div class="bg-dark-grey d-flex align-items-center" style="height: 47vh; width: 96.625%; border-radius: 20px; position: relative;">
        <div class="logo-bitcoin d-flex">
          <%= image_tag('btc1.png', size:"80")%>
          <h2 data-portfolios-target="value" style="font-size: 35px; margin-left: 20px;"></h2>
        </div>
        <canvas id="portfolioCanvas" aria-label="chart" role="img" class="my-auto">
          <h1> TOTAL BITCOIN</h1>
        </canvas>
      </div>
    </div>
  </div>


  <div class="bg-dark-grey">
    <div class="container p-5">
      <div class="row">
      <h2 class="d-flex" data-controller="edit-portfolio-name"
          data-edit-portfolio-name-authenticity-token-value="<%= form_authenticity_token %>"
          data-edit-portfolio-name-portfolio-id-value="<%= @portfolio.id %>">
      <span data-edit-portfolio-name-target="portfolioName" data-action="focusout->edit-portfolio-name#finishEdit keydown->edit-portfolio-name#finishEdit">
      <%= @portfolio.name %>
      </span> <div class="link-white align-self-center px-3" data-action="click->edit-portfolio-name#edit"><i class="fa-solid fa-pencil"></i></div></h2>

      <div class="col-12 col-lg-6">
        <div class="d-flex justify-content-between align-items-center">
          <h3 class="text-pink font-rainbows my-4">ADDRESSES</h3>
          <a href="<%= portfolios_path %>" class="d-flex link-white mx-4">
            <i class="fa-solid fa-arrow-left p-1"></i>PROFILE
          </a>
        </div>

        <%# LIST DES ADDRESSES %>
        <div data-controller="balance" class="addresses-grid">
          <% @portfolio.addresses.each do |address| %>
            <div class="container-address">
              <%= link_to address_path(address), class: "w-100" do %>
                <div class="icone-title">
                  <div class="d-flex" style="align-items: center;">
                    <%= image_tag("logocard.png", class: "img-bitcoin") %>
                    <div>
                      <h2 id="title-btc"><strong>BITCOIN</strong></h2>
                    </div>
                  </div>
                </div>

                <div class="key-balance" style=" font-size: 10px; margin-bottom: -5px; margin-top: -7px; padding-top: 9px;">
                    <div>
                      <p id="paragraphe-card"><%= "#{address.public_key[0..7]}...#{address.public_key[-8..-1]}"%></p>
                    </div>
                    <div>
                      <p id="value-crypto-card-address"><strong data-balance-target="balance" data-address="<%= address.public_key %>"></strong></p>
                    </div>
                </div>

              <% end %>
              <%= link_to address_path(address), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?"}, class: 'text-danger' do %>
                <i class="fas fa-trash trash-icone-value"></i>
              <% end %>
            </div>
          <% end %>

          <%# ADD CARD %>
          <div class="container-address clickable" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <button type="button" id="btn-plus" class="btn"><h1><strong>+</strong></h1></button>
          </div>




        </div>
      </div>

      <%# HISTORIQUE TRANSACTION %>
      <div class="col-12 col-lg-6">
        <h3 class="text-pink font-rainbows my-4">RECENT TRANSACTIONS</h3>
        <div data-portfolios-target="transactions">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add Address Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ADD AN ADDRESS</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for(@address) do |f|%>
      <div class="modal-body">
      <%= f.hidden_field :portfolio_id, value: @portfolio.id %>
      <%= f.input :public_key, label:"public key", label_html: { class: "text-white" }, placeholder:"bc1q5crsrfueudwyfekp..." %>
      </div>
      <div class="modal-footer">
        <%= f.submit "SAVE", class:"btn btn-secondary" %>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_address_form.html.erb
<div class="nested-form-wrapper my-3 d-flex justify-content-between gap-3" data-new-record="<%= f.object.new_record? %>">
  <%= f.text_field :public_key, placeholder: 'bc1q5crsrfueudwyfekp...', class: "form-control-v2" %>
  <button type="button" data-action="nested-form#remove" class="trash-form"><i class="fas fa-trash trash-icone-value-v2"></i></button>
  <%= f.hidden_field :_destroy %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container mg-5 footer-links">
    <div class="sizeiconefooterV0"><p>© 2023 Coins, Inc. All rights reserved</p></div>
    <div class="sizeiconefooterV1"><a href="https://github.com/etoriaz/coins"><i class="fab fa-github"></i></a></div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon display-nav">

  <div><h1><%= link_to "COINS", root_path, class:"font-rainbows logo"%></h1>
  </div>

  <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="navbar-items d-flex">
          <a><%= link_to "LOG OUT", destroy_user_session_path, data: { "turbo-method": :delete }, class:"btn-navbar2" %></a>
          <%= link_to(portfolios_path) do %>
            <%= image_tag("thibovf.png", size: '42x42', class: 'profile-image-navbar')%>
          <% end %>
          </li>
      </ul>
    </div>

  <% else %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="navbar-items">
            <a><%= link_to "SIGN UP", new_user_registration_path, class:"btn-navbar"%></a>
          </li>
          <li class="navbar-items">
            <a><%= link_to "LOG IN", user_session_path, class:"btn-navbar"%></a>
          </li>
      </ul>
    </div>
  <% end %>
</div>